### ISSUE TITLE
Selecting an item and the mouse quickly changes selection before drag is started

### ISSUE THREAD

**Issue by punker76** [punker76/gong-wpf-dragdrop#1]
_Original author: gro...@gmail.com (November 07, 2009 19:14:39)_

When clicking an item and moving the mouse quickly, rather than a drag on the 
item that was clicked on being dragged, sometimes the selection changes 
before the drag is started. This is particularly noticeable if clicking the 
item causes the UI to lock up for a short time.

_Original issue: http://code.google.com/p/gong-wpf-dragdrop/issues/detail?id=1_

**Comment by SuicSoft** [comment]
So how about closing this if there is a fix, since this is ancient from 2009 :smile: (the old days where the web wasn't so advanced (needed plugins) and Windows 7 was new and now we're in 2015 with Windows 10 and advanced web technologies and modern software (android and ios apps, windows 10 etc)). Anyways i don't think the original author will ever try the work-around . So we should just close this. Or you can try tweaking the code

First issue on this github repo :smile:



PS: Google Code already read-only and will close down in the start 2016
