### ISSUE TITLE
Adding a grip handle to list box item as a drag source

### ISSUE THREAD

**Issue by folksmotion** [punker76/gong-wpf-dragdrop#114]
There are couple of issues and questions:

1. When using gong dd wpf library it mixes click and drag/drop events. My listboxitem comprises of complex data template in which there are checkbox, combobox, textbox etc. How to prevent this click, mouse down and drag/drop event from being captured on all controls in listboxitem datatemplate?

2. How to confine only to a grip handle instead of making whole listboxitem as drag source?

Thanks in advance. 
Any help and suggestion is greatly appreciated.

**Comment by rwg0** [comment]
Various controls are ignored when the drag starts over them - for instance any sort of button, etc. However some complex controls such as Expander are built on a ButtonBase, so cannot be dragged because 
`HitTestUtilities.HitTest4Type<ButtonBase>(sender, elementPosition)`
returns true in `DragSource_PreviewMouseLeftButtonDown`.

This commit - https://github.com/rwg0/gong-wpf-dragdrop/commit/d9e561972c4e06c558f865aa37718b3c9cfffe28 - adds a very simple DragHandle that can be used to wrap any XAML control. If the initial drag point hits a DragHandle then the change makes the drag start regardless of the result of the other `HitTestUtilities.HitTest4Type<T>` calls.

Not sure whether this solves the general problem but it certainly makes it easy for me to put a DragHandle into the UI of an Expander and then drag the whole expander.

**Comment by punker76** [comment]
@folksmotion This should now work as expected (see https://github.com/punker76/gong-wpf-dragdrop/issues/187). Please take a look to the latest source and the `Cloning` sample.
