### ISSUE TITLE
System.IO.FileNotFoundException after install via nuget

### ISSUE THREAD

**Issue by wowfood** [punker76/gong-wpf-dragdrop#240]
System.IO.FileNotFoundException: 'Could not load file or assembly 'GongSolutions.WPF.DragDrop, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'

This appears when the software attempts to parse a xaml file with the following namespace.

    xmlns:dd="urn:gong-wpf-dragdrop"

also occurs if this namespace is used.

    xmlns:dd="clr-namespace:GongSolutions.Wpf.DragDrop;assembly=GongSolutions.Wpf.DragDrop"

Might be to do with new visual studio version, not sure.

### Environment

- GongSolutions.WPF.DragDrop __v1.1.0
- Windows OS Windows 7 Professional, SP1
- Visual Studio 2017
- .NET Framework 4.6.2

**Comment by wowfood** [comment]
not sure how to close this, but it can now be closed.  Visual studio was being obnoxious, after a full cleanup / removeing .sou and all the other stuff it's now magically moving the dll to th correct location and working fine.

**Comment by Indigo744** [comment]
I'm sorry to re-open an old closed thread, but since I have the exact same issue, I think it make sense to continue the discussion here. Feel free to tell me to open a new thread if you want.

So, as I said, I happen to have the exact same issue... And I'm banging my head at it since several hours, without a shred of success... 😞 

## Error message

Basically, I got same message as @wowfood but in French:  `Could not load file or assembly '...' or one of its dependencies. The system cannot find the file specified.`

The message differs between version on the `PublicKeyToken`.

**With version v1.1.0**
`
System.Windows.Markup.XamlParseException : FileNotFoundException : 'Impossible de charger le fichier ou l'assembly 'GongSolutions.WPF.DragDrop, PublicKeyToken=null' ou une de ses dépendances. Le fichier spécifié est introuvable.'
`

**With latest version v2.0.1**
`
System.Windows.Markup.XamlParseException : FileNotFoundException : 'Impossible de charger le fichier ou l'assembly 'GongSolutions.WPF.DragDrop, PublicKeyToken=91f1945125b7a587' ou une de ses dépendances. Le fichier spécifié est introuvable.'
`

## Environment
 - Windows 10 Pro 1809
 - Visual Studio 2017
 - Project : .NET Framework 4.5

## XAML code sample

Don't know if it's relevant, but anyway.

I only followed the first part of the usage wiki page by adding `dd:DragDrop.*` to my `ItemsControl`.

```xaml
<!--  Widgets  -->
<ItemsControl
	dd:DragDrop.IsDragSource="True"
	dd:DragDrop.IsDropTarget="True"
	ItemsSource="{Binding Path=Widgets}">
	<ItemsControl.ItemsPanel>
		<ItemsPanelTemplate>
			<WrapPanel IsItemsHost="True" />
		</ItemsPanelTemplate>
	</ItemsControl.ItemsPanel>
</ItemsControl>
```

## What I tried

 - Full cleanup of solution, full re-regenerate
 - Deleting `.suo` solution file 
 - Deleting `packages` solution folder
 - Trying version 1.1.0 and 2.0.1
 - Trying different xmlns (`xmlns:dd="urn:gong-wpf-dragdrop"` and `xmlns:dd="clr-namespace:GongSolutions.Wpf.DragDrop;assembly=GongSolutions.Wpf.DragDrop"` )

I'm out of idea... I need your help.

@wowfood can you be more precise with the "_and all the other stuff_"?

Thanks a lot.
