### ISSUE TITLE
DragDrop on DataGrid Crashes application with error "A Drag Operation is already in progress"

### ISSUE THREAD

**Issue by iamwyza** [punker76/gong-wpf-dragdrop#253]
## What steps will reproduce this issue?

* Download current source for Showcase.WPF.DragDrop.Debug.
* Build
* Run
* Select DataGrid
* Attempt to drag a row

### Expected outcome

Row Drags

### Repo

This is in the vanilla sample application

### Environment

- GongSolutions.WPF.DragDrop v1.1.0 (also trunk)
- Windows OS 10
- Visual Studio 2017
- .NET Framework 4.6.2

**Comment by punker76** [comment]
@iamwyza I can't reproduce this with the current source.

**Comment by NeilBurkholder** [comment]
It seems the issue happens when another app is in the middle of a drop. In my case the other app was asking for approval before continuing with the drop. I fixed the issue by canceling the drop if this exception occurs. You may want to implement this fix in your repository.

![image](https://user-images.githubusercontent.com/24275193/40620786-1aa88fe4-6268-11e8-8332-b2973c20d296.png)
