### ISSUE TITLE
Logical tree depth exceeded while traversing the tree.

### ISSUE THREAD

**Issue by mrbrennonwilliams** [punker76/gong-wpf-dragdrop#280]
The full error is 
**InvalidOperationException** : Logical tree depth exceeded while traversing the tree. This could indicate a cycle in the tree

This is occurring in a drop operation of a IDropTarget, right at the end - .Add(sourceItem);.

```
  if (dropInfo.DragInfo.SourceCollection != null)
                {
                    if (dropInfo.DragInfo.SourceCollection is ItemCollection)
                        (dropInfo.DragInfo.SourceCollection as ItemCollection).Remove(sourceItem);
                    else
                        (dropInfo.DragInfo.SourceCollection as IList).Remove(sourceItem);
                }
                if (dropInfo.TargetCollection != null)
                {
                    if (dropInfo.TargetCollection is ItemCollection)
                        (dropInfo.TargetCollection as ItemCollection).Add(sourceItem);
                    else
                        (dropInfo.TargetCollection as IList).Add(sourceItem);
                }
```

Traditionally this is a binding error, but this is not the case here.

What is happening is that the sourceItem is already apart of the TargetCollection. How is that possible?

In the image below, the BLACK container (and all the child elements) are separate controls. Container 0 and ImageSet 1 both have ItemsControl bound to gong. The Image controls do not.

Important to note that the light gray around the container and image controls, is also a separate control which has a ItemsControl bound to gong. So we are looking at multiple nested ItemControls.

The bottom most IMAGE block is outside of the BLACK container, yet when I start a drag from it, the entire container above is shown as the drag adorner. 

![dragcapture](https://user-images.githubusercontent.com/32671341/32983632-969135da-cc8f-11e7-9c49-ed9030f6efc9.png)

Effectively I am then dropping a Container back into itself - hence the original error.

I am sure I am doing something incorrect, which is easily explainable. But for the life of me, I dont understand how a drag on a control can be registered as a drag of a completely separate control?

Thoughts and help would be really appreciated.

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/punker76/gong-wpf-dragdrop/releases) and then please use the [issue template](https://github.com/punker76/gong-wpf-dragdrop/issues/new).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/gong-wpf-dragdrop) and [appveyor](https://ci.appveyor.com/project/punker76/gong-wpf-dragdrop/history), [appveyor feed](https://ci.appveyor.com/nuget/gong-wpf-dragdrop)).

Thank you! 🙏

**Comment by Gholamalih** [comment]
The exception thrown, when we drop something into itself.
