### ISSUE TITLE
can we drag and drop controls between tabs. we want to move say a text box control from one tab to another

### ISSUE THREAD

**Issue by rohit-b** [punker76/gong-wpf-dragdrop#286]

**Comment by punker76** [comment]
@rohit-b I don't know if this makes sense to use directly the textbox control, but you can drag drop between tabs with a placeholder, a model/class or something else.

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/punker76/gong-wpf-dragdrop/releases) and then please use the [issue template](https://github.com/punker76/gong-wpf-dragdrop/issues/new).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/gong-wpf-dragdrop) and [appveyor](https://ci.appveyor.com/project/punker76/gong-wpf-dragdrop/history), [appveyor feed](https://ci.appveyor.com/nuget/gong-wpf-dragdrop)).

Thank you! 🙏
