### ISSUE TITLE
ListBox SelectionChanged raised during drag-drop

### ISSUE THREAD

**Issue by abhilashca** [punker76/gong-wpf-dragdrop#326]
Hello,

I have WPF application where items in ListBox can be reordered by drag-drop. The ListBox has SelectionChanged event to perform an action when an item is selected. When I do drag-drap in the ListBox, SelectionChanged event is triggered. Is there any way, I can stop raising SelectionChanged during drag-drop?

Is there any suggested way to handle this?

Thanks.

**Comment by uecasm** [comment]
Clicking on an item initially selects that item, and the actual drag-drop doesn't start until after this.  Furthermore the drag-drop typically applies to all selected items, not just the one where the drag actually started on, so it has to select the item being clicked before the drag starts, or it wouldn't be dragging the right items.

After the drop completes, the items are now in a different order (or added or removed), which means that the SelectedIndicies have changed, so a SelectionChanged is appropriately fired then as well.

So, unless I'm misunderstanding you, I don't think it makes sense to not change the selection during drag-drop.

**Comment by amalwbpro** [comment]
I do agree and understand that you need to select an item (which fires `SelectionChanged` event) prior to drag an item. Now, this results in secnarios like I mentioned earlier. If I have code written in `SelectionChanged` event, then while doing a drag, the `SelectionChanged` event gets fired.

How to handle this? I don't want to trigger a `SelectionChanged` event while I am doing a drag action.

What I am doing right now is, I moved code inside SelectionChanged event to a Task with delay. Then, I listed to other events to know whether a drag is active. When the delay is over, I'll decide whether to execute the logic or not based on a flag. Thought this works, this add delay for ideal scenario - selecting an item, also.

Any thoughts on best way to handle this?

**Comment by uecasm** [comment]
My question is what you're doing on selection that shouldn't apply to dragging, given that you have to select something before you drag it anyway.  (So by definition, you can't ever drag something that is not selected, which naturally means that selection change does have to fire _at some point_ before a drag.)

Now, if your problem is that you're getting one SelectionChanged, and then you're getting another SelectionChanged with the **same** set of items, and _then_ a drag, then that might be a bug, but it's also something you can easily check for and filter yourself.

Besides, if you use MVVM properly then you don't use SelectionChanged at all, you instead bind to SelectedItem/SelectedItems/IsSelected.

**Comment by punker76** [comment]
@abhilashca Did the answers help?

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/punker76/gong-wpf-dragdrop/releases) and then please use the [issue template](https://github.com/punker76/gong-wpf-dragdrop/issues/new).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/gong-wpf-dragdrop) and [appveyor](https://ci.appveyor.com/project/punker76/gong-wpf-dragdrop/history), [appveyor feed](https://ci.appveyor.com/nuget/gong-wpf-dragdrop)).

Thank you! 🙏
