### ISSUE TITLE
Wrong ObservableCollection EventArg after  drag/drop

### ISSUE THREAD

**Issue by tonecool** [punker76/gong-wpf-dragdrop#355]
I'm using ObservableCollection<T> which is bound to ItemsControl ItemsSource property. 

What I expect to get after drag and drop an item within control is NotifyCollectionChangedAction.Move event like this:

```
        private void MyCollection_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.Action == NotifyCollectionChangedAction.Move)
            {
                //DO something
            }
        }
```

But instead I'm getting two events (NotifyCollectionChangedAction.Remove and NotifyCollectionChangedAction.Add). I'm not sure if this is by design but in my case it was complicating the logic to decide if there was new item added externally or just drag/dropped existing control item.

### Repo
I can provide code example if needed.
### Environment

- GongSolutions.WPF.DragDrop 2.2.0
- Windows 10
- Visual Studio 2019
- .NET Framework 4.7.2

**Comment by punker76** [comment]
@tonecool I think that's because the default drop handler uses the RemoveAt and Insert methods of the source and destination. If you know that's always the same then you can implement your own drop handler which then uses the move method. If you find a solution then you can try to add this here and make a PR. Thx 🙏

**Comment by Mogikan** [comment]
Use case when it's important: you need to implement Undo/Redo. Because when you undo it deletes an item, but does not paste it back.
