### ISSUE TITLE
shared item source cause RelativeSource bug.

### ISSUE THREAD

**Issue by a44281071** [punker76/gong-wpf-dragdrop#372]
I have a collection named `Items`.

I have a `DataGrid` bind `ItemsSource` to `Items` and add drag handler.

I have another `ListBox` and just display `Items` as tile view to display image data.

```

  // Listbox.ItemTemplate
  <my:DisplayControl TargetElement="{Binding RelativeSource={RelativeSource AncestorType={x:Type ListBoxItem}}}"/>

  // Bug: TargetElement will get '{DisconnectedItem}' after drag drop.
```

**Comment by punker76** [comment]
@a44281071 Hi, sorry for the late response.

> // Bug: TargetElement will get '{DisconnectedItem}' after drag drop.

I don't know what you mean with this. Is this a output from your app?

Normally if the Items are the same, then all should work automatically. Or have you custom handlers for the drag&drop operations?

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/punker76/gong-wpf-dragdrop/releases) and then please use the [issue template](https://github.com/punker76/gong-wpf-dragdrop/issues/new).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/gong-wpf-dragdrop) and [appveyor](https://ci.appveyor.com/project/punker76/gong-wpf-dragdrop/history), [appveyor feed](https://ci.appveyor.com/nuget/gong-wpf-dragdrop)).

Thank you! 🙏
