### ISSUE TITLE
I use SetDropHandler in the control to set the IDropTarget interface class.  But told me it didn't happen  

### ISSUE THREAD

**Issue by ms1094392787** [punker76/gong-wpf-dragdrop#427]
![image](https://user-images.githubusercontent.com/49998334/150276203-7615ce46-e15a-4256-ac11-4c555b2f9dec.png)

![image](https://user-images.githubusercontent.com/49998334/150276179-292834e9-17c0-483d-9eba-ab828c7736fa.png)

![image](https://user-images.githubusercontent.com/49998334/150276280-aaaa351e-a061-439a-bc41-38fca6ddbe4e.png)

**Comment by punker76** [comment]
@ms1094392787 Where do you set the `IsDropTarget` property for your listbox?

**Comment by punker76** [comment]
@ms1094392787 

I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/punker76/gong-wpf-dragdrop/releases) and then please use the [issue template](https://github.com/punker76/gong-wpf-dragdrop/issues/new).

If you have enough time then it would be nice to test this issue against the latest alpha version (available via [NuGet](https://www.nuget.org/packages/gong-wpf-dragdrop) and [appveyor](https://ci.appveyor.com/project/punker76/gong-wpf-dragdrop/history), [appveyor feed](https://ci.appveyor.com/nuget/gong-wpf-dragdrop)).

Thank you! 🙏
