### ISSUE TITLE
DropTargetAdorner ZIndex

### ISSUE THREAD

**Issue by zdy1988** [punker76/gong-wpf-dragdrop#460]
When I create a control over on the **listview**，the **DropTargetAdorner** not covered！

like this：

![1668406210(1)](https://user-images.githubusercontent.com/6028407/201588599-82a51be3-2df7-4e88-9e77-a2179e91ed71.jpg)

but, **treeview** no problem

![1668406250(1)](https://user-images.githubusercontent.com/6028407/201588671-8566e3ce-c6fb-422b-a33d-6b9b0faab41a.jpg)
![1668406278(1)](https://user-images.githubusercontent.com/6028407/201588682-391732d2-7c64-4edf-88df-aac143853427.jpg)

In the process of practical application, this problem occurs when the listview contains a horizontal scroll bar...

**Comment by Mideks** [comment]
I have a similar problem when I use ListBox
When I use a ListBox with a scrollbar, for some reason `DropTargetInsertionAdorner`(probably) is not displayed correctly at all, and this is very confusing.
I have described in sufficient detail here: 
https://stackoverflow.com/questions/75118372/reordering-listbox-elements-with-gong-wpf-dragdrop-causes-visual-bugs

But since, most likely, I won't be able to get any help, I decided to come to you
